In [1]:
import pandas as pd

In [2]:
print(pd)

<module 'pandas' from 'c:\\Users\\sarbj\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages\\pandas\\__init__.py'>

In [3]:
df=pd.read_csv("Netflix.csv.xls")

Now add first 5 Rows

In [4]:
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,15-01-22,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,05-09-21,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,28-02-23,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,10-07-22,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,01-05-23,28-06-23,Germany,33,Male,Smartphone,1 Month

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User ID            2500 non-null   int64
 1   Subscription Type  2500 non-null   str
 2   Monthly Revenue    2500 non-null   int64
 3   Join Date          2500 non-null   str
 4   Last Payment Date  2500 non-null   str
 5   Country            2500 non-null   str
 6   Age                2500 non-null   int64
 7   Gender             2500 non-null   str
 8   Device             2500 non-null   str
 9   Plan Duration      2500 non-null   str
dtypes: int64(3), str(7)
memory usage: 195.4 KB

In [6]:
df.isna().sum()

User ID              0
Subscription Type    0
Monthly Revenue      0
Join Date            0
Last Payment Date    0
Country              0
Age                  0
Gender               0
Device               0
Plan Duration        0
dtype: int64

In [7]:
df["Join Date"]=pd.to_datetime(df["Join Date"])

C:\Users\sarbj\AppData\Local\Temp\ipykernel_17296\3973860675.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Join Date"]=pd.to_datetime(df["Join Date"])

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User ID            2500 non-null   int64
 1   Subscription Type  2500 non-null   str
 2   Monthly Revenue    2500 non-null   int64
 3   Join Date          2500 non-null   datetime64[us]
 4   Last Payment Date  2500 non-null   str
 5   Country            2500 non-null   str
 6   Age                2500 non-null   int64
 7   Gender             2500 non-null   str
 8   Device             2500 non-null   str
 9   Plan Duration      2500 non-null   str
dtypes: datetime64[us](1), int64(3), str(6)
memory usage: 195.4 KB

In [9]:
df["Last Payment Date"]=pd.to_datetime(df["Last Payment Date"])

C:\Users\sarbj\AppData\Local\Temp\ipykernel_17296\4002640718.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Last Payment Date"]=pd.to_datetime(df["Last Payment Date"])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User ID            2500 non-null   int64
 1   Subscription Type  2500 non-null   str
 2   Monthly Revenue    2500 non-null   int64
 3   Join Date          2500 non-null   datetime64[us]
 4   Last Payment Date  2500 non-null   datetime64[us]
 5   Country            2500 non-null   str
 6   Age                2500 non-null   int64
 7   Gender             2500 non-null   str
 8   Device             2500 non-null   str
 9   Plan Duration      2500 non-null   str
dtypes: datetime64[us](2), int64(3), str(5)
memory usage: 195.4 KB

In [11]:
df["Year"]=df["Join Date"].dt.year

In [12]:
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,Year
0,1,Basic,10,2022-01-15,2023-10-06,United States,28,Male,Smartphone,1 Month,2022
1,2,Premium,15,2021-05-09,2023-06-22,Canada,35,Female,Tablet,1 Month,2021
2,3,Standard,12,2023-02-28,2023-06-27,United Kingdom,42,Male,Smart TV,1 Month,2023
3,4,Standard,12,2022-10-07,2023-06-26,Australia,51,Female,Laptop,1 Month,2022
4,5,Basic,10,2023-01-05,2023-06-28,Germany,33,Male,Smartphone,1 Month,2023

In [13]:
df["Month"]=df["Join Date"].dt.month

In [75]:
df["Date"]=df["Join Date"].dt.date

In [14]:
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,Year,Month
0,1,Basic,10,2022-01-15,2023-10-06,United States,28,Male,Smartphone,1 Month,2022,1
1,2,Premium,15,2021-05-09,2023-06-22,Canada,35,Female,Tablet,1 Month,2021,5
2,3,Standard,12,2023-02-28,2023-06-27,United Kingdom,42,Male,Smart TV,1 Month,2023,2
3,4,Standard,12,2022-10-07,2023-06-26,Australia,51,Female,Laptop,1 Month,2022,10
4,5,Basic,10,2023-01-05,2023-06-28,Germany,33,Male,Smartphone,1 Month,2023,1

#using map function

In [15]:
df["Gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [16]:
df["Gender"]=df["Gender"].map({"Male":"M","Female":"F"})

In [17]:
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,Year,Month
0,1,Basic,10,2022-01-15,2023-10-06,United States,28,M,Smartphone,1 Month,2022,1
1,2,Premium,15,2021-05-09,2023-06-22,Canada,35,F,Tablet,1 Month,2021,5
2,3,Standard,12,2023-02-28,2023-06-27,United Kingdom,42,M,Smart TV,1 Month,2023,2
3,4,Standard,12,2022-10-07,2023-06-26,Australia,51,F,Laptop,1 Month,2022,10
4,5,Basic,10,2023-01-05,2023-06-28,Germany,33,M,Smartphone,1 Month,2023,1

Again we can use map function

In [18]:
df["Gender"]=df["Gender"].map({"M":"Male","F":"Female"})

In [19]:
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,Year,Month
0,1,Basic,10,2022-01-15,2023-10-06,United States,28,Male,Smartphone,1 Month,2022,1
1,2,Premium,15,2021-05-09,2023-06-22,Canada,35,Female,Tablet,1 Month,2021,5
2,3,Standard,12,2023-02-28,2023-06-27,United Kingdom,42,Male,Smart TV,1 Month,2023,2
3,4,Standard,12,2022-10-07,2023-06-26,Australia,51,Female,Laptop,1 Month,2022,10
4,5,Basic,10,2023-01-05,2023-06-28,Germany,33,Male,Smartphone,1 Month,2023,1

now checking the unique values in subscribtion type [column]

In [20]:
df["Subscription Type"].unique()

<StringArray>
['Basic', 'Premium', 'Standard']
Length: 3, dtype: str

In [21]:
df["Country"].unique()

<StringArray>
[ 'United States',         'Canada', 'United Kingdom',      'Australia',
        'Germany',         'France',         'Brazil',         'Mexico',
          'Spain',          'Italy']
Length: 10, dtype: str

if we want to check total number of unique values or count of unique values we can use the nunique()

In [22]:
df["Country"].nunique()

10

#Value Counts
means particular column wich ohna diya values da count.
am gonna using column "Country" iss ch pta lga ki countries kinni war repeated hai.

In [23]:
df["Country"].value_counts()

Country
United States     451
Spain             451
Canada            317
United Kingdom    183
Australia         183
Germany           183
France            183
Brazil            183
Mexico            183
Italy             183
Name: count, dtype: int64

#using Groupby function

In [24]:
type(df)

pandas.DataFrame

In [25]:
df.groupby("Subscription Type")

Explanation:
. Pehla data nu Subscription Type de according 3 groups (Basic, Premium, Standard) vich divide kita janda hai.
. Fir har group di Monthly Revenue da total (Sum) calculate kita janda hai.

Output:
. Basic → Basic group de sare users di total Monthly Revenue.
. Premium → Premium group de sare users di total Monthly Revenue.
. Standard → Standard group de sare users di total Monthly Revenue.

In [26]:
df.groupby("Subscription Type")["Monthly Revenue"].sum()

Subscription Type
Basic       12469
Premium      9229
Standard     9573
Name: Monthly Revenue, dtype: int64

Explanation:
. Pehla data nu Subscription Type de according 3 groups (Basic, Premium, Standard) vich divide kita janda hai.
. Fir har group di Monthly Revenue di average (Mean) calculate kiti jandi hai.

Output:
. Basic → Basic group de users di average Monthly Revenue.
.Premium → Premium group de users di average Monthly Revenue.
.Standard → Standard group de users di average Monthly Revenue.

Conclusion:
Mean function har group di average Monthly Revenue dikhaunda hai.

In [27]:
df.groupby("Subscription Type")["Monthly Revenue"].mean()

Subscription Type
Basic       12.481481
Premium     12.590723
Standard    12.464844
Name: Monthly Revenue, dtype: float64

Now we can find that basic wale kinne users hai and premium wale kinne te standard wale kinne si.
size() function har group wich kinne kinne users hai oh count ya pta lganda hai.

In [28]:
df.groupby("Subscription Type").size()

Subscription Type
Basic       999
Premium     733
Standard    768
dtype: int64

In [29]:
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,Year,Month
0,1,Basic,10,2022-01-15,2023-10-06,United States,28,Male,Smartphone,1 Month,2022,1
1,2,Premium,15,2021-05-09,2023-06-22,Canada,35,Female,Tablet,1 Month,2021,5
2,3,Standard,12,2023-02-28,2023-06-27,United Kingdom,42,Male,Smart TV,1 Month,2023,2
3,4,Standard,12,2022-10-07,2023-06-26,Australia,51,Female,Laptop,1 Month,2022,10
4,5,Basic,10,2023-01-05,2023-06-28,Germany,33,Male,Smartphone,1 Month,2023,1

min() nal eh pta lgga ki har group de bnde like basic, premuim, and standard ne kam se kam kinna revenue dita.

In [30]:
df.groupby("Subscription Type")["Monthly Revenue"].min()

Subscription Type
Basic       10
Premium     10
Standard    10
Name: Monthly Revenue, dtype: int64

max() means jada jada toh jada kinna dita

In [31]:
df.groupby("Subscription Type")["Monthly Revenue"].max()

Subscription Type
Basic       15
Premium     15
Standard    15
Name: Monthly Revenue, dtype: int64

pehla country de groups bnaye ki kiniya countries include hai

In [32]:
df.groupby("Country")

pher alag alag country de total kinne users hai oh check kitte

In [33]:
df.groupby("Country").size()

Country
Australia         183
Brazil            183
Canada            317
France            183
Germany           183
Italy             183
Mexico            183
Spain             451
United Kingdom    183
United States     451
dtype: int64

In [36]:
df["Country"].unique()

<StringArray>
[ 'United States',         'Canada', 'United Kingdom',      'Australia',
        'Germany',         'France',         'Brazil',         'Mexico',
          'Spain',          'Italy']
Length: 10, dtype: str

In [37]:
df["Country"].nunique()

10

In [38]:
df.groupby("Country")["Monthly Revenue"].sum()

Country
Australia         2271
Brazil            2285
Canada            3950
France            2307
Germany           2260
Italy             2317
Mexico            2237
Spain             5662
United Kingdom    2318
United States     5664
Name: Monthly Revenue, dtype: int64

In [39]:
df.groupby("Country")["Monthly Revenue"].mean()

Country
Australia         12.409836
Brazil            12.486339
Canada            12.460568
France            12.606557
Germany           12.349727
Italy             12.661202
Mexico            12.224044
Spain             12.554324
United Kingdom    12.666667
United States     12.558758
Name: Monthly Revenue, dtype: float64

In [40]:
df.groupby("Country")["Monthly Revenue"].max()

Country
Australia         15
Brazil            15
Canada            15
France            15
Germany           15
Italy             15
Mexico            15
Spain             15
United Kingdom    15
United States     15
Name: Monthly Revenue, dtype: int64

In [41]:
df.groupby("Country")["Monthly Revenue"].min()

Country
Australia         10
Brazil            10
Canada            10
France            10
Germany           10
Italy             10
Mexico            10
Spain             10
United Kingdom    10
United States     10
Name: Monthly Revenue, dtype: int64

In [42]:
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,Year,Month
0,1,Basic,10,2022-01-15,2023-10-06,United States,28,Male,Smartphone,1 Month,2022,1
1,2,Premium,15,2021-05-09,2023-06-22,Canada,35,Female,Tablet,1 Month,2021,5
2,3,Standard,12,2023-02-28,2023-06-27,United Kingdom,42,Male,Smart TV,1 Month,2023,2
3,4,Standard,12,2022-10-07,2023-06-26,Australia,51,Female,Laptop,1 Month,2022,10
4,5,Basic,10,2023-01-05,2023-06-28,Germany,33,Male,Smartphone,1 Month,2023,1

In [43]:
df.groupby("Gender")

size()lga ke pta lga ke male and females kiniya hai

In [46]:
df.groupby("Gender").size()

Gender
Female    1257
Male      1243
dtype: int64

sum() pta lga ki kinne kinna revenue dita  females ne sub toh bhad revenue dita

In [48]:
df.groupby("Gender")["Monthly Revenue"].sum()

Gender
Female    15736
Male      15535
Name: Monthly Revenue, dtype: int64

now we gonnna check ki device wise kon kinna revenue de reha hai means phone wala person kinna dinda and laptop use krn wala 
kinna dinda and so on..

In [52]:
df["Device"].unique()

<StringArray>
['Smartphone', 'Tablet', 'Smart TV', 'Laptop']
Length: 4, dtype: str

In [53]:
df.groupby("Device")["Monthly Revenue"].sum()

Device
Laptop        7994
Smart TV      7615
Smartphone    7691
Tablet        7971
Name: Monthly Revenue, dtype: int64

In [54]:
df.groupby("Device").size()

Device
Laptop        636
Smart TV      610
Smartphone    621
Tablet        633
dtype: int64

now analysis according to age

In [55]:
df["Age"].unique()

array([28, 35, 42, 51, 33, 29, 46, 39, 37, 44, 31, 45, 48, 27, 38, 36, 30,
       43, 32, 41, 26, 34, 49, 40, 47, 50])

In [56]:
df.groupby("Age")["Monthly Revenue"].sum()

Age
26      15
27    1101
28    1438
29    1317
30    1475
31    1413
32    1156
33    1161
34    1091
35    1325
36    1225
37    1326
38    1115
39    1460
40    1271
41    1447
42    1261
43    1190
44    1087
45    1127
46    1229
47    1406
48    1233
49    1214
50    1051
51    1137
Name: Monthly Revenue, dtype: int64

In [57]:
df.groupby("Age")["Monthly Revenue"].max()

Age
26    15
27    15
28    15
29    15
30    15
31    15
32    15
33    15
34    15
35    15
36    15
37    15
38    15
39    15
40    15
41    15
42    15
43    15
44    15
45    15
46    15
47    15
48    15
49    15
50    15
51    15
Name: Monthly Revenue, dtype: int64

#16 grouby+count   count column wich null values count or ginda hai.

In [67]:
df.groupby("Subscription Type")["User ID"].count()

Subscription Type
Basic       999
Premium     733
Standard    768
Name: User ID, dtype: int64

#17 Mulptiple groupby

In [68]:
df.groupby(["Country","Subscription Type"])["Monthly Revenue"].sum()

Country         Subscription Type
Australia       Basic                 378
                Premium              1254
                Standard              639
Brazil          Basic                1824
                Premium               410
                Standard               51
Canada          Basic                1816
                Premium              1086
                Standard             1048
France          Basic                 445
                Premium              1862
Germany         Basic                1833
                Premium                36
                Standard              391
Italy           Basic                2223
                Premium                55
                Standard               39
Mexico          Basic                  46
                Standard             2191
Spain           Basic                1386
                Premium              2689
                Standard             1587
United Kingdom  Basic                  35
                Standard             2283
United States   Basic                2483
                Premium              1837
                Standard             1344
Name: Monthly Revenue, dtype: int64

In [69]:
df.groupby(["Country","Subscription Type"])["Monthly Revenue"].mean()

Country         Subscription Type
Australia       Basic                12.193548
                Premium              12.415842
                Standard             12.529412
Brazil          Basic                12.493151
                Premium              12.424242
                Standard             12.750000
Canada          Basic                12.524138
                Premium              12.340909
                Standard             12.476190
France          Basic                12.361111
                Premium              12.666667
Germany         Basic                12.302013
                Premium              12.000000
                Standard             12.612903
Italy           Basic                12.630682
                Premium              13.750000
                Standard             13.000000
Mexico          Basic                11.500000
                Standard             12.240223
Spain           Basic                12.600000
                Premium              12.683962
                Standard             12.302326
United Kingdom  Basic                11.666667
                Standard             12.683333
United States   Basic                12.477387
                Premium              12.668966
                Standard             12.560748
Name: Monthly Revenue, dtype: float64

asi es ch check kita country wise basic,preimuim,standard users har country ch kinne hai

In [70]:
df.groupby(["Country","Subscription Type"]).size()

Country         Subscription Type
Australia       Basic                 31
                Premium              101
                Standard              51
Brazil          Basic                146
                Premium               33
                Standard               4
Canada          Basic                145
                Premium               88
                Standard              84
France          Basic                 36
                Premium              147
Germany         Basic                149
                Premium                3
                Standard              31
Italy           Basic                176
                Premium                4
                Standard               3
Mexico          Basic                  4
                Standard             179
Spain           Basic                110
                Premium              212
                Standard             129
United Kingdom  Basic                  3
                Standard             180
United States   Basic                199
                Premium              145
                Standard             107
dtype: int64

#18  multiple groupby+ multiple columns

In [78]:
df.groupby(["Country","Gender","Subscription Type"])[["Monthly Revenue","User ID"]].sum()

                                         Monthly Revenue  User ID
Country        Gender Subscription Type
Australia      Female Basic                          191    22424
                      Premium                        558    55445
                      Standard                       352    29842
               Male   Basic                          187    19410
                      Premium                        696    69389
                      Standard                       287    15307
Brazil         Female Basic                          951    93636
                      Premium                        194    20977
                      Standard                        11      307
               Male   Basic                          873    75856
                      Premium                        216    20969
                      Standard                        40      621
Canada         Female Basic                          867    79396
                      Premium                        488    59073
                      Standard                       618    72801
               Male   Basic                          949    88679
                      Premium                        598    62984
                      Standard                       430    49719
France         Female Basic                          216    16977
                      Premium                        930    86089
               Male   Basic                          229    25824
                      Premium                        932    83293
Germany        Female Basic                          978    83880
                      Premium                         10       85
                      Standard                       160    17370
               Male   Basic                          855    85550
                      Premium                         26      620
                      Standard                       231    24495
Italy          Female Basic                         1082   105930
                      Premium                         40      780
                      Standard                        26      480
               Male   Basic                         1141   105325
                      Premium                         15      160
                      Standard                        13      240
Mexico         Female Basic                           23      166
                      Standard                      1068   101561
               Male   Basic                           23      766
                      Standard                      1123   110056
Spain          Female Basic                          745    93210
                      Premium                       1444   148435
                      Standard                       738    77961
               Male   Basic                          641    67751
                      Premium                       1245   139001
                      Standard                       849    88106
United Kingdom Female Basic                           25      316
                      Standard                      1161   108903
               Male   Basic                           10      383
                      Standard                      1122   102032
United States  Female Basic                         1301   150364
                      Premium                        918    81372
                      Standard                       641    77710
               Male   Basic                         1182   134617
                      Premium                        919    86966
                      Standard                       703    82641

#19 Groupby+  Value_counts

In [79]:
df.groupby(["Country","Subscription Type"])["Device"].value_counts()

Country        Subscription Type  Device
Australia      Basic              Smartphone    11
                                  Laptop         8
                                  Tablet         7
                                  Smart TV       5
               Premium            Smartphone    29
                                                ..
United States  Premium            Smartphone    28
               Standard           Tablet        33
                                  Smart TV      30
                                  Laptop        24
                                  Smartphone    20
Name: count, Length: 99, dtype: int64

#20 Correlation matrix

In [80]:
df.corr(numeric_only=True)

                  User ID  Monthly Revenue       Age      Year     Month
User ID          1.000000        -0.004809  0.008065 -0.107841  0.129357
Monthly Revenue -0.004809         1.000000 -0.021143 -0.026703  0.011999
Age              0.008065        -0.021143  1.000000 -0.023296  0.038118
Year            -0.107841        -0.026703 -0.023296  1.000000 -0.116590
Month            0.129357         0.011999  0.038118 -0.116590  1.000000

#21 Selected columns correlation 
selected columns correleration shows the relationship between only selected numeric columns

In [81]:
df[["Age","Monthly Revenue"]].corr()

                      Age  Monthly Revenue
Age              1.000000        -0.021143
Monthly Revenue -0.021143         1.000000