In [41]:
import pandas as pd

In [42]:
import matplotlib.pyplot as plt

In [43]:
import numpy as np

In [44]:
import seaborn as sns

In [45]:
import plotly.express as px

In [46]:
df=pd.read_csv("employess attrition.csv")

In [47]:
df.shape

(1470, 35)

In [48]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [49]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [50]:
df.nunique()

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 510.8 KB

In [52]:
df.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [55]:
df.drop(columns=["EmployeeCount","Over18","StandardHours"],inplace=True)

In [56]:
df.shape

(1470, 32)

In [57]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='str')

                    Exploratory Data Analysis(EDA) Data Visualization

 ### Attrition Distribution

In [58]:
att=df["Attrition"].value_counts()
att

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [59]:
department_count=df

In [60]:
df["Department"].unique()

<ArrowStringArray>
['Sales', 'Research & Development', 'Human Resources']
Length: 3, dtype: str

In [61]:
depar_count=df.groupby("Department").size().reset_index(name="Total Employees")
fig=px.bar(
    depar_count,
    x="Department",y="Total Employees",
    color="Department",
    text="Total Employees",
    title="Total Employees by Department",
    hover_data={
        "Department":True,
        "Total Employees":True
    }

    )
fig.update_traces(
textposition="outside",
marker_line_color="black",
marker_line_width=1.5


)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,height=500,
    width=800,
    showlegend=True
    
)
fig.show()

Age Distribution of the Workforce

In [62]:
fig=px.histogram(
    df,
    x="Age",
    nbins=10,
    title="Age Distribution of the Workforce",

    color_discrete_sequence=px.colors.qualitative.Pastel1,
    text_auto="True",
    hover_data={"Age":True}
)
fig.update_traces(
    marker_line_color="black",
    marker_line_width=1.9,


)
fig.update_layout(
    template="plotly_white",
    title_font=dict(size=22),
    height=500,
    width=800,
    title_x=0.5,
    showlegend=True,
    yaxis_title="Count of Employees",
    xaxis_title="Age Distribution of Employees",
    hoverlabel=dict(
        bgcolor="red",
        font_color="white"
    )

)
fig.show()

Gender Diversity Across Roles [Treemap]

In [63]:
fig=px.treemap(
    df,
    path=["JobRole","Gender"],
    title="Gender Distribution Across Job Roles",
    color="Gender",
    color_discrete_sequence=["blue","pink"],
    hover_data={ 
    "JobRole":True,"Gender":True
    }
)
fig.update_traces(
    textfont=dict(size=15),
    marker_line_width=5,
    marker_line_color="black",
    root_color="lightgrey",textinfo="label+value"
    
) 
fig.update_layout(
    template="plotly_white",
    title_font=dict(size=22),
    height=700,
    width=1000,
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="red",
        font_color="white"
    ))
fig.show()

Marital Status Breakdown[Pie Chart]  It helps HR understand how employees are divided into:
 Single, Married, and Divorced categories.

In [64]:
marital_count=df.groupby("MaritalStatus").size().reset_index(name="Count")
fig=px.pie(
    marital_count,
    names="MaritalStatus",
    values="Count",
    title="Marital Status Breakdown",
    color="MaritalStatus",
    color_discrete_sequence=px.colors.qualitative.Dark24,
)
fig.update_traces(
    textinfo="label+percent",
    hole=0.4
)
fig.update_layout(
    title_font_size=40,
    height=700,
    width=900,
    template="plotly_dark"



)

[Employee Attrition OverView]

This shows the number of employees who left the company and who are still working.

In [65]:
attrition_count=df.groupby("Attrition").size().reset_index(name="Count")
fig=px.bar(
    attrition_count,
    x="Attrition",
    y="Count",
    title="<b>Employee Attrition Overview</b>",
    color="Attrition",
    text_auto=True,
    )
fig.update_layout(
    title_x=0.5,
    xaxis_title="Attrition",
    yaxis_title="Number of Employees",
    template="plotly_white",
    height=500,
    width=700
)
fig.update_traces(
    textposition="outside"

)
fig.show()

[Department With the Highest Employee Attrition]:

 It shows the job roles where more employees leave the company

In [66]:
df["Department"].unique()

<ArrowStringArray>
['Sales', 'Research & Development', 'Human Resources']
Length: 3, dtype: str

In [83]:
employees_left=df[df["Attrition"]=="Yes"]
fig=px.sunburst(
    employees_left,
    path=["Department","JobRole"],
    color="Department",
    color_discrete_sequence=px.colors.qualitative.Dark24,
    
    title="Employee Attrition by Department and Job Role"
)

fig.update_traces(
    textinfo="label+value",
    textfont_size=14,textfont_color="black"
)
fig.update_layout(
    title_x=0.3,
    template="plotly_dark",
    width=1000,
    height=800,
    hoverlabel=dict(
        bgcolor="white",
        font_color="blue",
        font_size=12)
    
    )


fig.show()

In [68]:
df["JobRole"].unique()

<ArrowStringArray>
[          'Sales Executive',        'Research Scientist',
     'Laboratory Technician',    'Manufacturing Director',
 'Healthcare Representative',                   'Manager',
      'Sales Representative',         'Research Director',
           'Human Resources']
Length: 9, dtype: str

[Employees Attrition by JobRole]

In [69]:
employees_left=df[df["Attrition"]=="Yes"]
jobs=employees_left.groupby("JobRole").size().reset_index(name="Count")
fig=px.bar(
jobs,
x="JobRole",
y="Count",
title="Employees Left by Job Role",
text_auto=True,
color="JobRole",
color_discrete_sequence=px.colors.qualitative.Pastel
)
fig.update_traces(
textfont_size=12,
marker_line_color="black",
marker_line_width=3
)

fig.update_layout(
    title_x=0.4,
    xaxis_title="Job Role",
    yaxis_title="Number of Employees",
    hoverlabel=dict(
        bgcolor="white",
          font_color="red"  ),
          font_color="black",
          font_size=13

)
fig.show()

Attrition Trend by Years At Company

In [70]:
employees_left=df[df["Attrition"]=="Yes"]
years=employees_left.groupby("YearsAtCompany").size().reset_index(name="count")
fig=px.line(
    years,
    x="YearsAtCompany",
    y="count",
    title="Attrition Trend Years by Company",
    markers=True
)
fig.update_traces(
    line_color="green",
    line_width=3,
    marker=dict(
        size=7,
        color="red"
    ),
    
)
fig.update_layout(
    title_x=0.4,
    xaxis_title="Years at Company",
    yaxis_title="Employees Left",
    
)


fig.show()

In [71]:
fig=px.scatter( 
    df,
    x="Age",
    y="MonthlyIncome",
    color="Attrition",
    color_discrete_sequence=px.colors.qualitative.Dark24,
    
    title="<b> Monthly Income VS Age by Attrition Status</b>",
    hover_data=["JobRole","Department"]



)

fig.update_traces(
    marker=dict(
        size=7,
        opacity=1,
        symbol="star"
    )
)
fig.update_layout(
    title_x=0.4,
    hoverlabel=dict(
    bgcolor="white",
    font_color="black" ,
    font_size=13
    ),
    xaxis_title="Age",
    paper_bgcolor="black",
    plot_bgcolor="black",
    font =dict(size =13,color="white")

)


fig.show()

In [72]:
fig=px.box(
    df,
    x="JobRole",
    y="MonthlyIncome",
    title="<b>Monthly Income Distribution Job Roles</b>",
    color="JobRole",
    points="outliers",
    color_discrete_sequence=px.colors.qualitative.Bold,
)
fig.update_layout(
title_x=0.4,
title_font_size=25,
xaxis_title="Job Role",
yaxis_title="Monthly Income",
template="plotly_dark",
showlegend=True,

)

fig.update_traces(
    hoverlabel=dict(
        bgcolor="white",
        font_color="black"
    )

)


fig.show()

In [73]:
fig=px.violin(
    df,
    x="PerformanceRating",
    y="JobSatisfaction",
    box=True,
    points="all",
    title="<b> Job Satisfaction Across Performance Ratings</b>"



)
fig.update_traces(
    line_color="black",
    fillcolor="yellow",
    box_line_color="red",
    box_fillcolor="pink"
),
fig.update_layout(
    xaxis_title="Performance Rating",
    yaxis_title="Job Satisfaction",
    template="plotly_dark",
    title_x=0.4
)
fig.show()

In [74]:

num_df = df[
    [
        "Age",
        "MonthlyIncome",
        "DistanceFromHome",
        "PercentSalaryHike",
        "WorkLifeBalance"
    ]
]
corr_matrix = num_df.corr()

fig = px.imshow(
    corr_matrix,
    text_auto=True,
    color_continuous_scale=px.colors.qualitative.Bold,
    title="<b>Correlation of Numerical Metrics</b>"
)

# Update Layout
fig.update_layout(
    title_x=0.5,
    xaxis_title="Numerical Columns",
    yaxis_title="Numerical Columns",
    template="plotly_white",
    font=dict(size=14),
    width=1000,height=700
)

fig.show()

In [75]:
fig = px.box(
    df,
    x="Gender",
    y="MonthlyIncome",
    title="<b>Monthly Income by Gender</b>",
    color="Gender",
    color_discrete_map={
        "Male":"blue",
        "Female":"red"
    },
    points="outliers"

)

fig.update_layout(
    title_x=0.5,
    template="plotly_dark"
)

fig.show()

Check how monthly income varies across different department

In [76]:
df["MonthlyIncome"].unique()

array([5993, 5130, 2090, ..., 9991, 5390, 4404], shape=(1349,))

In [77]:
fig=px.violin(
    df,
    x="Department",
    y="MonthlyIncome",
    color="Department",
    box=True,
    points="all",
    title="<b>Monthly Income by Department</b>",
    color_discrete_sequence=px.colors.qualitative.Bold,


)
fig.update_traces(
    marker=dict(size=4),
line=dict(width=2),

)
fig.update_layout(
    title_x=0.4,
    title_font_size=29,
    height=600,
    width=1000,
    xaxis_title="Department",
    yaxis_title="Monthly Income",
    template="plotly_dark",
    font=dict(size=15),
    hoverlabel=dict(
        bgcolor="white",
        font_color="red"
    ),
    font_color="white",


)
fig.show()

Check whether the didtence from home affects job satisfaction.

In [78]:
fig = px.scatter(
    df,
    x="DistanceFromHome",
    y="JobSatisfaction",
    color="DistanceFromHome",
    title="<b>Distance From Home vs Job Satisfaction</b>",
    color_discrete_sequence=px.colors.qualitative.Bold,
    hover_data=["Department", "JobRole", "MonthlyIncome"]
)

fig.update_traces(
    marker=dict(size=10)
)

fig.update_layout(
    title_x=0.5,
    title_font_size=24,
    xaxis_title="Distance From Home",
    yaxis_title="Job Satisfaction",
    template="plotly_dark",
    font=dict(size=14),
    hoverlabel=dict(
        bgcolor="white",
        font_color="black",
        font_size=14
    )
)

fig.show()

Check the percentage of employess who work overtime....

In [79]:
fig = px.pie(
    df,
    names="OverTime",
    title="<b>Employees Working Overtime</b>",
    color="OverTime",
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.update_traces(
    textinfo="percent+label",
    textfont_size=15,
    pull=[0,0.08]
)
fig.update_layout(
    title_x=0.5,
    title_font_size=30,
    template="plotly_dark"
)
fig.show()

Compare the number of male and female employees in eash education field

In [80]:
data=df.groupby(["EducationField","Gender"]).size().reset_index(name="Count of Employees")
fig=px.bar(
data,
x="EducationField",
y="Count of Employees",
color="Gender",
color_discrete_sequence=px.colors.qualitative.Bold,
title="<b>Male and Female Employees By Education Field</b>"
)
fig.update_layout(
    title_x=0.5,
    title_font_size=24,
    xaxis_title="Education Field",
    yaxis_title="Number of Employees",
    template="plotly_dark",
    font=dict(size=14),

)

fig.show()